SEED: 0
TRAIN:
    batch_size: 16
    epochs: 100
    num_workers: 0
    input_track_size: 9
    output_track_size: 12
    lr: 0.0001
    lr_decay: 1
    lr_drop: true
    aux_weight: 0.2
    val_frequency: 5
    optimizer: "adam"
    max_grad_norm: 1.0
DATA:
    train_datasets:
        - jrdb_2dbox
MODEL:
    seq_len: 30 
    token_num: 2
    num_layers_local: 6
    num_layers_global: 3
    num_heads: 4
    dim_hidden: 128 
    dim_feedforward: 1024 
    type: "transmotion"
    eval_single: false
    checkpoint: "" 
    output_scale: 1 
